name: SynUI

on:
  push:
    branches: "**"
    
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
    
permissions: write-all

jobs:
  build:
#    strategy:
#      matrix:
#        configuration: [ Debug, Release ]

    runs-on: windows-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Path: .\SynUI.sln # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the version
        uses: dotnet/nbgv@v0.4.0
        id: nbgv
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
      
      # Restore the application
      - name: Restore the application
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: nuget restore "${{ env.Project_Path }}"
      
      # Build the application
      - name: Build the application
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild -m -p:Configuration="Release" "${{ env.Project_Path }}"
      
      # Package the application
      - name: Package the application
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          & "SynUI.Setup\bin\Release\SynUI.Setup.exe"
      
      # List files
      - name: List files
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          & tree
      
      # Upload the application
      - name: Upload artifacts (Setup)
        uses: actions/upload-artifact@v3
        with:
          name: Setup
          path: Output\setup.exe

      - name: Upload artifacts (Portable)
        uses: actions/upload-artifact@v3
        with:
          name: Portable
          path: SynUI\bin\Release\
